Introduction to tensors


1. getting information forom tensors
2. manipulating tensors
3. Tensors and nupy
4. Using @tf function
5. using GPU and TPU



In [3]:
# import tensor flow

import tensorflow as tf

print(tf.__version__)


2.9.2


## **CREATING A TENSOR WITH** tf.constant

In [4]:
# Creating Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check number of dimensions

scalar.ndim

0

In [6]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# check dimension of vector
vector.ndim

1

In [8]:
# create a matirx
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# new matrix along with dtype
another_matrix = tf.constant(
    [[1.,2.],[3.,4.]],
    dtype='float16'
)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [11]:
tensor = tf.constant(
    [[[1,2,3],
      [4,5,6]],
     [[7,8,9],
      [9,10,11]]]
)
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 9, 10, 11]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we have created so far
* Scalar: a single number
* vector: a number with diresction
* matrix: a 2D array of numbers
* Tensor: an nD array of numbers(
  where n  can be any number,
  a,0 dimensional tensor is scalar,
  a 1- dimensional tensor is a vector
)

## **CREATING A TENSOR WITH** tf.Variable

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# assign tensor directly
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [15]:
# assigning values in tensor using assign method
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [16]:
# try to change a unchangeable tensor
unchangeable_tensor[0].assign(7)

AttributeError: ignored

## CREATING RANDOM TENSORS 
Random tensors are some arbitary arrays that contain random numbers

In [17]:
# create two random tensors
random_tensor_1 = tf.random.Generator.from_seed(7)
random_tensor_1 = random_tensor_1.normal(shape=(3,2))
random_tensor_2 = tf.random.Generator.from_seed(7)
random_tensor_2 = random_tensor_2.normal(shape=(3,2))

# checking equality
random_tensor_1,random_tensor_2,random_tensor_1 == random_tensor_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## SHUFFLE THE ORDER OF ELEMENTS IN A TENSOR

In [26]:
# shuffle a tensor
not_shuffled = tf.constant([
    [10,7],
    [3,4],
    [2,5]
])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [30]:
# using a shuffle method from random
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>